gems:
  - jekyll-sitemap
  - jekyll-mentions
exclude:
  - Rakefile
  - pids
  - Gemfile*

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "autolink", "tables", "with_toc_data"]

permalink: pretty

jekyll-mentions: https://twitter.com

author:
    name:    François Monniot
    email:   francois@monniot.eu
    github:  https://github.com/fmonniot
    twitter: https://twitter.com/fmonniot
    gplus:   http://plus.google.com/+FrançoisMonniot

site:
    name: François Monniot
    url:  http://francois.monniot.eu/
