markdown: rdiscount
permalink: pretty
exclude:
  - Rakefile
  - pids
  - README.md
  - this.sublime-project
  - this.sublime-workspace
paginate: 3
lang: fr

author:
    name: François Monniot
    email: francois@monniot.eu
    github: fmonniot
    twitter: fmonniot
    gplusto: fmonniot

    #75 characters max
    description: This is yet a short description of myself. Try to keep it short.

site:
    name: "François Monniot"
    url:  "http://francois.monniot.eu/"
