gems:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-paginate

exclude:
  - Rakefile
  - pids
  - Gemfile*

include:
  - .well-known

markdown: kramdown

future: true
permalink: pretty
paginate: 150 # Only to have access to paginator.total_posts

jekyll-mentions: https://twitter.com

author:
    name:     François Monniot
    email:    francois@monniot.eu
    github:   https://github.com/fmonniot
    twitter:  https://twitter.com/fmonniot
    gplus:    https://plus.google.com/+FrançoisMonniot
    linkedin: https://linkedin.com/in/fmonniot

name: François Monniot
url:  http://francois.monniot.eu/

sass:
  style: :compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "wrapped"
