markdown: redcarpet
permalink: pretty
exclude:
  - Rakefile
  - pids
  - this.sublime-project
  - this.sublime-workspace
  - Gemfile*
paginate: 3
lang: en

author:
    name:    François Monniot
    email:   francois@monniot.eu
    github:  https://github.com/fmonniot
    twitter: https://twitter.com/fmonniot
    gplus:   http://plus.google.com/+FrançoisMonniot

site:
    name: François Monniot
    url:  http://francois.monniot.eu/
