source 'https://rubygems.org'

#ruby=ruby-2.1.0

gem 'albino'
gem 'chronic'
gem 'classifier'
gem 'directory_watcher'
gem 'fast-stemmer'
gem 'jekyll'
gem 'jekyll-localization'
gem 'jekyll-rendering'
gem 'kramdown'
gem 'liquid'
gem 'maruku'
gem 'posix-spawn'
gem 'syntax'
gem 'jekyll-less'
gem 'therubyracer'
gem 'redcarpet'
gem 'pygments.rb'
gem 'pdfkit'
gem 'nokogiri'
